name: test_build_publish
on:
  push:
    branches:
      - main

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        run: |
          docker run --rm --privileged tonistiigi/binfmt:latest --install all
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - uses: actions/checkout@v3
      - run: go run ci/dagger.go test
      - run: tail -n +1 output/*/*/*.out
      - run: go run ci/dagger.go push
      - run: tail -n +1 output/*/*/*.out